# Generated by Django 5.2.11 on 2026-08-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='rentengine_status',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Raw listing status from RentEngine's /units endpoint. Free text, not a choices enum — RentEngine's vocabulary is larger than what appears in our data and can change. Current state only; not historical.", max_length=50),
        ),
    ]
