# Generated by Django 5.2.14 on 2026-08-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_unit_rentengine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='rentengine_advertised_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Advertised listing rent from RentEngine's /units endpoint. Distinct from target_rental_rate, which comes from RentVine and is the target rent, not the advertised price. Null means unknown; never zero.", max_digits=10, null=True),
        ),
    ]
