# Generated by Django 5.2 on 2026-10-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_unit_rentengine_advertised_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='contact_first_name',
            field=models.CharField(
                blank=True,
                help_text=(
                    "First name of the human contact linked to this entity owner's "
                    "portfolio(s). Populated during sync for entity owners (empty or "
                    "digit-starting first_name). Used for email greetings."
                ),
                max_length=100,
            ),
        ),
    ]
