# Generated by Django 5.2.11 on 2026-02-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leasing', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boompay_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('applicant_name', models.CharField(blank=True, max_length=255)),
                ('applicant_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_applications', to='leasing.application')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_applications', to='properties.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boompay_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('report_type', models.CharField(choices=[('credit', 'Credit Report'), ('criminal', 'Criminal Background'), ('eviction', 'Eviction History'), ('income', 'Income Verification'), ('landlord_ref', 'Landlord Reference'), ('identity', 'Identity Verification')], max_length=20)),
                ('decision', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('review', 'Needs Review'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screening_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='screening.screeningapplication')),
            ],
        ),
    ]
