# Generated by Django 5.2.11 on 2026-07-29 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentengine_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('prospect_type', models.CharField(blank=True, default='', max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='core.unit')),
            ],
        ),
        migrations.CreateModel(
            name='LeasingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentengine_id', models.IntegerField(db_index=True, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('event_timestamp', models.DateTimeField(db_index=True)),
                ('event_date', models.DateField(db_index=True)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('planned_date_time', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('property_address', models.CharField(blank=True, default='', max_length=500)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leasing_events', to='core.unit')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='leasing.prospect')),
            ],
            options={
                'ordering': ['-event_timestamp'],
                'indexes': [models.Index(fields=['unit', 'event_date'], name='ix_leasevent_unit_date'), models.Index(fields=['unit', 'event_type', 'event_date'], name='ix_leasevent_unit_type_date')],
            },
        ),
    ]
