# Generated by Django 5.2.11 on 2026-08-16 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentEngineWebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target_entity', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('operation', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('unparseable', 'Unparseable'), ('ignored', 'Ignored')], db_index=True, max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('resulting_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_deliveries', to='leasing.leasingevent')),
                ('resulting_prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_deliveries', to='leasing.prospect')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
