# Generated by Django 5.2.11 on 2026-02-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rent from recurring charges where account.isRent', max_digits=10, null=True),
        ),
    ]
