# Generated by Django 5.2.11 on 2026-02-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_add_lease_rent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='pet_rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pet rent portion (subset of rent_amount) from Pet Rent account charges', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross monthly rent from active recurring charges where account.isRent', max_digits=10, null=True),
        ),
    ]
