# Generated by Django 5.2.11 on 2026-08-17 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('leasing', '0002_rentenginewebhookdelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitLeasingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('new_leads', models.IntegerField(default=0)),
                ('showings_scheduled', models.IntegerField(default=0)),
                ('showings_completed', models.IntegerField(default=0)),
                ('showings_canceled', models.IntegerField(default=0)),
                ('showings_missed', models.IntegerField(default=0)),
                ('applications_received', models.IntegerField(default=0)),
                ('touchpoints_calls', models.IntegerField(blank=True, null=True)),
                ('touchpoints_texts', models.IntegerField(blank=True, null=True)),
                ('upcoming_showings', models.IntegerField(blank=True, null=True)),
                ('days_on_market', models.IntegerField(blank=True, null=True)),
                ('property_health', models.CharField(blank=True, default='', max_length=50)),
                ('reporting_fetch_ok', models.BooleanField(default=False)),
                ('reporting_error', models.TextField(blank=True, default='')),
                ('reporting_raw', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leasing_snapshots', to='core.unit')),
            ],
            options={
                'ordering': ['-period_start', 'unit_id'],
                'unique_together': {('unit', 'period_start', 'period_end')},
            },
        ),
    ]
