# Generated by Django 5.2.14 on 2026-08-17 01:16

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_unit_rentengine_advertised_rent'),
        ('leasing', '0003_unitleasingsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioLeasingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, default='weekly', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('notes_html', models.TextField(blank=True, default='', help_text='Rendered HTML fragment for the leasing section (inline-styled for SendGrid).')),
                ('generated_note', models.TextField(blank=True, default='', help_text='AI-generated plain-text note (the raw output, before human review).')),
                ('approved_generated_note', models.TextField(blank=True, default='', help_text='Human-reviewed/edited version of generated_note. Blank = not yet reviewed.')),
                ('unit_snapshot', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Frozen per-unit context including prior-week values, captured at generation. Source for rebuilding notes_html on edit.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], db_index=True, default='draft', max_length=10)),
                ('is_edited', models.BooleanField(db_index=True, default=False, help_text="True once a human has edited this note's snapshot. Protects it from being overwritten on regeneration. Set False on fresh generation.")),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leasing_notes', to='core.portfolio')),
            ],
            options={
                'indexes': [models.Index(fields=['period_type', 'period_start', 'status'], name='leasing_por_period__8793d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'period_type', 'period_start'), name='unique_leasing_note_per_period')],
            },
        ),
    ]
