# Generated by Django 5.2.11 on 2026-03-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0003_add_pet_rent_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('announcement_sent_at', models.DateTimeField(blank=True, null=True)),
                ('referral_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-first_seen_at'],
            },
        ),
    ]
