# Generated by Django 5.2.11 on 2026-08-18 01:13

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0004_portfolioleasingnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioleasingnote',
            name='edited_notes',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Per-unit edited AI note text, keyed by str(unit_id). Overrides ai_result.unit_summaries when re-rendering notes_html.'),
        ),
        migrations.AlterField(
            model_name='portfolioleasingnote',
            name='approved_generated_note',
            field=models.TextField(blank=True, default='', help_text='Human-reviewed/edited version of generated_note. Blank = not yet reviewed. NOT used by the dashboard edit path (preserved for future use).'),
        ),
    ]
