# Generated by Django 5.2.11 on 2026-05-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0004_knownlisting'),
        ('properties', '0003_portfolio_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLeasingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('new_prospects', models.IntegerField(default=0)),
                ('showings_completed', models.IntegerField(default=0)),
                ('applications_submitted', models.IntegerField(default=0)),
                ('showings_missed_or_failed', models.IntegerField(default=0)),
                ('days_on_market', models.IntegerField(blank=True, null=True)),
                ('property_health', models.CharField(blank=True, choices=[('Off-Market', 'Off-Market'), ('Healthy', 'Healthy'), ('At-risk', 'At-risk'), ('On Hold', 'On Hold'), ('Waitlist', 'Waitlist'), ('Commercial', 'Commercial'), ('Unknown', 'Unknown')], max_length=20, null=True)),
                ('benchmark_leads_since_last_price_change', models.IntegerField(blank=True, null=True)),
                ('showings_scheduled', models.IntegerField(blank=True, null=True)),
                ('applications_requested', models.IntegerField(blank=True, null=True)),
                ('active_prospects', models.IntegerField(blank=True, null=True)),
                ('upcoming_showings', models.IntegerField(blank=True, null=True)),
                ('outbound_texts', models.IntegerField(blank=True, null=True)),
                ('total_calls', models.IntegerField(blank=True, null=True)),
                ('showing_feedback_summary', models.JSONField(default=list)),
                ('source', models.CharField(choices=[('csv_backfill', 'CSV Backfill'), ('rentengine_api', 'RentEngine API')], max_length=20)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_leasing_metrics', to='properties.unit')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'unit'], name='leasing_dai_date_c6f876_idx')],
                'unique_together': {('unit', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ShowingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentengine_prospect_id', models.IntegerField(db_index=True)),
                ('prospect_name', models.CharField(max_length=255)),
                ('showing_completed_at', models.DateTimeField(db_index=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showing_feedbacks', to='properties.unit')),
            ],
            options={
                'unique_together': {('rentengine_prospect_id', 'showing_completed_at')},
            },
        ),
    ]
