# Generated by Django 5.2.11 on 2026-05-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0005_add_leasing_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasingevent',
            name='event_type',
            field=models.CharField(choices=[('new', 'New'), ('contacted_awaiting_information', 'Contacted, Awaiting Information'), ('showing_desired', 'Showing Desired'), ('showing_scheduled', 'Showing Scheduled'), ('showing_confirmed', 'Showing Confirmed'), ('arrived_for_showing', 'Arrived for Showing'), ('showing_started', 'Showing Started'), ('showing_complete', 'Showing Complete'), ('missed_showing', 'Missed Showing'), ('showing_failed', 'Showing Failed'), ('showing_canceled', 'Showing Canceled'), ('showing_pending', 'Showing Pending'), ('reassign_showing', 'Reassign Showing'), ('ghosting', 'Ghosting'), ('application_sent_to_prospect', 'Application Sent to Prospect'), ('application_received', 'Application Received'), ('application_pending', 'Application Pending'), ('application_in_owner_review', 'Application in Owner Review'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('withdrawn', 'Withdrawn'), ('prescreen_submitted', 'Prescreen Submitted'), ('prescreen_rejected_credit', 'Prescreen Rejected - Credit'), ('prescreen_rejected_income', 'Prescreen Rejected - Income'), ('prescreen_rejected_id', 'Prescreen Rejected - ID Verification'), ('prescreen_approved', 'Prescreen Approved'), ('looking_too_early', 'Looking too early'), ('lease_out_for_signing', 'Lease out for signing'), ('lease_signed', 'Lease Signed'), ('deposit_received', 'Deposit Received'), ('move_in_scheduled', 'Move-in Scheduled'), ('moved_in', 'Moved In'), ('unit_of_interest_unavailable', 'Unit of Interest Unavailable'), ('not_interested', 'Not Interested'), ('duplicate_lead', 'Duplicate Lead'), ('still_deciding', 'Still Deciding'), ('hoa_application_sent', 'HOA Application Sent To Prospect'), ('hoa_application_submitted', 'HOA Application Submitted'), ('hoa_application_approved', 'HOA Application Approved'), ('hoa_application_rejected', 'HOA Application Rejected'), ('log_note', 'Log Note'), ('assign_to_user', 'Assign to User'), ('blocklist_prospect', 'Blocklist Prospect'), ('unblock_prospect', 'Unblock Prospect')], db_index=True, max_length=50),
        ),
    ]
