# Generated by Django 5.2.14 on 2026-08-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0005_portfolioleasingnote_edited_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitleasingsnapshot',
            name='advertised_date',
            field=models.DateField(blank=True, help_text='Start date of the current RentVine listing (listing.advertisedDate). Null means no active listing was found. Used to compute days on market as (period_end - advertised_date).days.', null=True),
        ),
        migrations.AlterField(
            model_name='unitleasingsnapshot',
            name='days_on_market',
            field=models.IntegerField(blank=True, help_text='Lifetime days-on-market from RentEngine. Retained in reporting_raw for comparison but no longer used in user-facing output — replaced by advertised_date from RentVine.', null=True),
        ),
    ]
