# Generated by Django 5.2.14 on 2026-08-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0006_unitleasingsnapshot_advertised_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitleasingsnapshot',
            name='date_marked_available',
            field=models.DateField(blank=True, help_text="RentEngine's date_marked_available for the current listing. Days on market is computed as (period_end - this).days - 1, matching RentEngine's UI which counts complete days elapsed.", null=True),
        ),
        migrations.AlterField(
            model_name='unitleasingsnapshot',
            name='advertised_date',
            field=models.DateField(blank=True, help_text='RentVine listing.advertisedDate. Retained for comparison with date_marked_available but no longer used in user-facing output.', null=True),
        ),
    ]
