# Generated by Django 5.2.11 on 2026-05-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0006_add_showing_pending_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyleasingmetric',
            name='applications_requested_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyleasingmetric',
            name='applications_submitted_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyleasingmetric',
            name='new_prospects_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyleasingmetric',
            name='outbound_texts_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyleasingmetric',
            name='showings_completed_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyleasingmetric',
            name='showings_missed_or_failed_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyleasingmetric',
            name='total_calls_delta',
            field=models.IntegerField(default=0),
        ),
    ]
