# Generated by Django 5.2.11 on 2026-05-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0007_add_delta_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyleasingmetric',
            name='source',
            field=models.CharField(choices=[('csv_backfill', 'CSV Backfill'), ('rentengine_api', 'RentEngine API'), ('webhook_realtime', 'Webhook Realtime')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leasingevent',
            name='rentengine_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='showing',
            name='rentengine_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CountedLeasingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentengine_event_id', models.IntegerField()),
                ('event_type', models.CharField(max_length=50)),
                ('counted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('rentengine_event_id', 'event_type')},
            },
        ),
    ]
