# Generated by Django 5.2.11 on 2026-08-24 02:03

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0007_unitleasingsnapshot_date_marked_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioleasingnote',
            name='recommended_actions',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Per-unit recommended action text, keyed by str(unit_id). Human-written in the dashboard, never AI-generated. Empty or missing means no action block renders for that unit.'),
        ),
    ]
