# Generated by Django 5.2.11 on 2026-08-25 00:31

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0008_portfolioleasingnote_recommended_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitleasingsnapshot',
            name='applications',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Application dicts for this unit and period. Each dict: group_id, status, submitted_at, num_applicants, workflow_step. workflow_step is DASHBOARD-ONLY — must never render in an owner email.'),
        ),
    ]
