# Generated by Django 5.2.11 on 2026-05-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0008_add_counted_leasing_event_and_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyleasingmetric',
            name='source',
            field=models.CharField(choices=[('csv_backfill', 'CSV Backfill'), ('rentengine_api', 'RentEngine API'), ('webhook_realtime', 'Webhook Realtime'), ('boompay', 'BoomPay')], max_length=20),
        ),
    ]
