# Generated by Django 5.2.11 on 2026-08-25 01:12

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_unit_rentengine_advertised_rent'),
        ('leasing', '0009_unitleasingsnapshot_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitleasingsnapshot',
            name='price_changes',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Price changes observed during this period. Each dict: old_rent, new_rent, detected_date. Empty when none.'),
        ),
        migrations.CreateModel(
            name='UnitPriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detected_date', models.DateField(db_index=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='core.unit')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['unit', 'detected_date'], name='ix_pricechange_unit_date')],
            },
        ),
    ]
