# Generated by Django 5.2.11 on 2026-08-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0012_applicationprocesscreation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentvineWebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('raw_headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(db_index=True, default='captured', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
