# Generated by Django 5.2.11 on 2026-09-07 16:25

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0013_rentvinewebhookdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitleasingsnapshot',
            name='since_listed',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Cumulative totals since date_marked_available, frozen at generation. Keys: leads, showings_scheduled, showings_completed, applications_received. Empty dict when the listing start date is unknown.'),
        ),
    ]
