# Generated by Django 5.2.11 on 2026-09-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0014_add_since_listed_to_unitleasingsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowingMaintenanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentengine_event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('prospect_rentengine_id', models.CharField(blank=True, default='', max_length=64)),
                ('unit_label', models.CharField(blank=True, default='', max_length=255)),
                ('note_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
