# Generated by Django 5.2.11 on 2026-02-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMarketStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, unique=True)),
                ('active_unit_count', models.IntegerField(default=0)),
                ('average_dom', models.IntegerField(default=0)),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('count_30_plus_dom', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'daily market stats',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyMarketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_month', models.DateField(db_index=True, unique=True)),
                ('average_dom', models.IntegerField(default=0)),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_30_plus_dom_count', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('total_leads', models.IntegerField(default=0)),
                ('total_showings', models.IntegerField(default=0)),
                ('total_missed_showings', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('lead_to_show_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('show_to_app_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-report_month'],
            },
        ),
        migrations.CreateModel(
            name='DailySegmentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('segment_type', models.CharField(choices=[('zip_code', 'Zip Code'), ('bedrooms', 'Bedrooms'), ('property_type', 'Property Type'), ('portfolio', 'Portfolio'), ('price_band', 'Price Band')], db_index=True, max_length=30)),
                ('segment_value', models.CharField(db_index=True, max_length=100)),
                ('active_unit_count', models.IntegerField(default=0)),
                ('average_dom', models.IntegerField(default=0)),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('count_30_plus_dom', models.IntegerField(default=0)),
                ('leads_count', models.IntegerField(default=0)),
                ('showings_count', models.IntegerField(default=0)),
                ('applications_count', models.IntegerField(default=0)),
                ('lead_to_show_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('show_to_app_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'daily segment stats',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['segment_type', 'segment_value'], name='market_dail_segment_5c033c_idx')],
                'unique_together': {('snapshot_date', 'segment_type', 'segment_value')},
            },
        ),
        migrations.CreateModel(
            name='PriceDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('detected_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='properties.unit')),
            ],
            options={
                'ordering': ['-detected_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyLeasingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField(db_index=True)),
                ('leads_count', models.IntegerField(default=0)),
                ('showings_completed_count', models.IntegerField(default=0)),
                ('showings_missed_count', models.IntegerField(default=0)),
                ('applications_count', models.IntegerField(default=0)),
                ('property_display_name', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_leasing_summaries', to='properties.unit')),
            ],
            options={
                'verbose_name_plural': 'daily leasing summaries',
                'ordering': ['-summary_date'],
                'unique_together': {('summary_date', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='DailyUnitSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('listed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('days_on_market', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('leased', 'Leased'), ('off_market', 'Off Market')], max_length=20)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('square_feet', models.IntegerField(blank=True, null=True)),
                ('date_listed', models.DateField(blank=True, null=True)),
                ('date_off_market', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='properties.unit')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['snapshot_date', 'status'], name='market_dail_snapsho_bcd870_idx')],
                'unique_together': {('unit', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyLeasingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ending', models.DateField(db_index=True)),
                ('leads_count', models.IntegerField(default=0)),
                ('showings_completed_count', models.IntegerField(default=0)),
                ('showings_missed_count', models.IntegerField(default=0)),
                ('applications_count', models.IntegerField(default=0)),
                ('lead_to_show_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('show_to_app_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('property_display_name', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_leasing_summaries', to='properties.unit')),
            ],
            options={
                'verbose_name_plural': 'weekly leasing summaries',
                'ordering': ['-week_ending'],
                'unique_together': {('week_ending', 'unit')},
            },
        ),
    ]
