# Generated by Django 5.2.11 on 2026-02-17 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('properties', '0002_property_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_date', models.DateField(db_index=True)),
                ('leased_date', models.DateField(blank=True, null=True)),
                ('lease_start_date', models.DateField(blank=True, null=True)),
                ('original_list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('signed_lease_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_dom', models.IntegerField(blank=True, null=True)),
                ('total_price_drops', models.IntegerField(default=0)),
                ('total_drop_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('list_to_lease_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='signed_lease_amount / original_list_price', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-listed_date'],
            },
        ),
        migrations.RenameField(
            model_name='pricedrop',
            old_name='change_amount',
            new_name='drop_amount',
        ),
        migrations.RenameField(
            model_name='pricedrop',
            old_name='change_percent',
            new_name='drop_percent',
        ),
        migrations.AddField(
            model_name='dailymarketstats',
            name='average_portfolio_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyunitsnapshot',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('leased_pending', 'Leased Pending'), ('occupied', 'Occupied'), ('make_ready', 'Make Ready')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricedrop',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_drops', to='properties.unit'),
        ),
        migrations.AddConstraint(
            model_name='pricedrop',
            constraint=models.CheckConstraint(condition=models.Q(('new_price__lt', models.F('previous_price'))), name='price_drop_must_be_downward'),
        ),
        migrations.AddField(
            model_name='listingcycle',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_cycles', to='properties.unit'),
        ),
        migrations.AddIndex(
            model_name='listingcycle',
            index=models.Index(fields=['unit', 'listed_date'], name='market_list_unit_id_377f33_idx'),
        ),
    ]
