# Generated by Django 5.2.11 on 2026-02-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_listingcycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySegmentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, help_text='First day of the month')),
                ('zip_code', models.CharField(db_index=True, max_length=20)),
                ('bedroom_count', models.IntegerField(db_index=True)),
                ('avg_occupied_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_list_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_dom', models.IntegerField(default=0)),
                ('avg_lease_length_months', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('leases_written_count', models.IntegerField(default=0)),
                ('total_leads', models.IntegerField(default=0)),
                ('total_showings', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('avg_credit_score', models.IntegerField(blank=True, null=True)),
                ('avg_applicant_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('occupied_unit_count', models.IntegerField(default=0)),
                ('vacant_unit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'monthly segment stats',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['zip_code', 'bedroom_count'], name='market_mont_zip_cod_511a61_idx')],
                'unique_together': {('month', 'zip_code', 'bedroom_count')},
            },
        ),
    ]
