# Generated by Django 5.2.11 on 2026-02-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_monthlysegmentstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymarketstats',
            name='median_dom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymarketstats',
            name='median_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
