# Generated by Django 5.2.11 on 2026-02-24 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_portfolio_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerReportNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('sent', 'Sent')], db_index=True, default='draft', max_length=10)),
                ('notes_text', models.TextField(blank=True)),
                ('email_body', models.TextField(blank=True)),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('report_date', models.DateField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_notes', to='properties.owner')),
            ],
            options={
                'ordering': ['-report_date', 'owner__name'],
                'unique_together': {('owner', 'report_date')},
            },
        ),
    ]
