# Generated by Django 5.2.11 on 2026-02-25 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('properties', '0003_portfolio_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notes', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
