# Generated by Django 5.2.11 on 2026-02-26 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboard_deep_dive_round2'),
        ('properties', '0003_portfolio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerreportnote',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerreportnote',
            name='properties_included',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ownerreportnote',
            name='sendgrid_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PropertyWeeklyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_date', models.DateField(db_index=True, help_text='Monday of the report week')),
                ('author', models.CharField(max_length=100)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_notes', to='properties.unit')),
            ],
            options={
                'ordering': ['-week_date'],
                'unique_together': {('unit', 'week_date')},
            },
        ),
    ]
