# Generated by Django 5.2.11 on 2026-03-25 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_ownerreportnote_delivery_fields'),
        ('properties', '0003_portfolio_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeldWeeklyDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True)),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('email_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], db_index=True, default='draft', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sendgrid_message_id', models.CharField(blank=True, max_length=255)),
                ('meld_count', models.IntegerField(default=0)),
                ('properties_included', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meld_drafts', to='properties.owner')),
            ],
            options={
                'ordering': ['owner__name'],
                'unique_together': {('owner', 'week_start')},
            },
        ),
    ]
