# Generated by Django 5.2.11 on 2026-05-19 20:57

from django.db import migrations, models


def backfill_approved(apps, schema_editor):
    """Mark all existing PropertyWeeklyNote rows as approved.

    Pre-existing notes were either AI-drafted via draft_all_property_notes,
    manually created, or imported — all were treated as approved before
    the approval workflow was introduced.
    """
    PropertyWeeklyNote = apps.get_model("dashboard", "PropertyWeeklyNote")
    PropertyWeeklyNote.objects.filter(approved=False).update(approved=True)


def reverse_backfill(apps, schema_editor):
    """Reverse: reset all to unapproved (safe since field is being removed)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_add_meldweeklydraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyweeklynote',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyweeklynote',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyweeklynote',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(backfill_approved, reverse_backfill),
    ]
