# Generated by Django 5.2.11 on 2026-05-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_add_approval_fields_to_propertyweeklynote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyweeklynote',
            name='week_date',
            field=models.DateField(db_index=True, help_text="Monday of the ISO calendar week containing the period's Tuesday start (i.e. the day before a Tue–Mon reporting window opens). Join key only; never shown to owners."),
        ),
    ]
