# Generated by Django 5.2.11 on 2026-02-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultifamilyProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentengine_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('text_address', models.CharField(blank=True, max_length=500)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'multifamily properties',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('reserve_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('additional_reserve_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('additional_reserve_description', models.TextField(blank=True)),
                ('fiscal_year_end_month', models.IntegerField(blank=True, null=True)),
                ('hold_distributions', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floorplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentengine_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multifamily_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floorplans', to='properties.multifamilyproperty')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_contact_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolios', models.ManyToManyField(blank=True, related_name='owners', to='properties.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('rentengine_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('property_type', models.CharField(blank=True, choices=[('single_family', 'Single Family Home'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('duplex', 'Duplex'), ('multiplex', 'Multiplex'), ('loft', 'Loft'), ('mobile_home', 'Mobile Home'), ('commercial', 'Commercial'), ('garage', 'Garage')], max_length=20)),
                ('is_multi_unit', models.BooleanField(default=False)),
                ('street_number', models.CharField(blank=True, max_length=20)),
                ('street_name', models.CharField(blank=True, max_length=255)),
                ('address_line_1', models.CharField(blank=True, max_length=500)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='US', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('management_fee_setting_id', models.IntegerField(blank=True, null=True)),
                ('maintenance_limit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reserve_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_contract_begins', models.DateField(blank=True, null=True)),
                ('date_contract_ends', models.DateField(blank=True, null=True)),
                ('date_insurance_expires', models.DateField(blank=True, null=True)),
                ('date_warranty_expires', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.portfolio')),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('rentengine_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address_line_1', models.CharField(blank=True, max_length=500)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('full_bathrooms', models.IntegerField(blank=True, null=True)),
                ('half_bathrooms', models.IntegerField(blank=True, null=True)),
                ('square_feet', models.IntegerField(blank=True, null=True)),
                ('target_rental_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multifamily_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='properties.multifamilyproperty')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
        ),
    ]
