# Generated by Django 5.2.11 on 2026-02-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='service_type',
            field=models.CharField(choices=[('full_management', 'Full Management'), ('leasing_only', 'Leasing Only'), ('maintenance_only', 'Maintenance Only')], default='full_management', max_length=20),
        ),
    ]
