# Generated by Django 5.2.11 on 2026-05-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_portfolio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='zillow_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
