# Generated by Django 5.2.11 on 2026-09-05 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_unit_rentengine_advertised_rent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reminder', 'Friendly Reminder (Day 5)'), ('pay_or_quit', 'Pay or Quit (Day 6)'), ('final', 'Final Notice (Day 11)')], db_index=True, max_length=20)),
                ('period_key', models.CharField(db_index=True, help_text="'YYYY-MM' of the rent period this notice concerns.", max_length=7)),
                ('rentvine_lease_id', models.IntegerField(db_index=True, help_text='RentVine lease ID - always populated, even when the FK is NULL.')),
                ('recipient_emails', models.JSONField(default=list, help_text='List of email addresses the notice was sent to.')),
                ('missing_recipients', models.JSONField(blank=True, default=list, help_text="Tenant names on the lease that had no email address at send time. Falls back to 'Contact #<id>' when no name is available.")),
                ('property_address', models.CharField(blank=True, default='', help_text='Display address frozen at send time (from Unit.display_address).', max_length=500)),
                ('balance_owed', models.DecimalField(decimal_places=2, help_text='Total outstanding balance at the time the notice was generated.', max_digits=12)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sendgrid_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_notices', to='core.lease')),
            ],
            options={
                'indexes': [models.Index(fields=['period_key', 'kind', 'delivery_status'], name='automations_period__d9181e_idx')],
                'constraints': [models.UniqueConstraint(fields=('rentvine_lease_id', 'kind', 'period_key'), name='unique_notice_per_lease_per_kind_per_period')],
            },
        ),
        migrations.CreateModel(
            name='TenantNoticeHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_lease_id', models.IntegerField(db_index=True, help_text='RentVine lease ID - always populated, even when the FK is NULL.')),
                ('period_key', models.CharField(blank=True, default='', help_text="'YYYY-MM' period to suppress. Blank = suppress all periods.", max_length=7)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_holds', to='core.lease')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rentvine_lease_id', 'period_key'), name='unique_hold_per_lease_per_period')],
            },
        ),
    ]
