# Generated by Django 5.2.11 on 2026-09-05 02:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantnotice',
            name='display_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Balance printed in the notice: rent, pet rent and late fees. May exceed balance_owed, which governs whether a notice is sent.', max_digits=12),
        ),
    ]
