from ninja import Schema


class OwnerOnboardIn(Schema):
    property_address: str
    property_city: str = ""
    property_zip: str = ""
    property_type: str = ""
    bedrooms: str = ""
    bathrooms: str = ""
    plan: str = ""
    owner1_name: str = ""
    owner1_email: str = ""
    owner1_phone: str = ""
    owner1_mailing: str = ""
    owner2_name: str = ""
    owner2_email: str = ""
    owner2_phone: str = ""
    owner2_mailing: str = ""
    poc_name: str = ""
    poc_email: str = ""
    poc_phone: str = ""
    occupied: str = ""
    transferring_pm: str = ""
    hoa: str = ""
    hoa_contact: str = ""
    warranty: str = ""
    warranty_company: str = ""
    water_source: str = ""
    water_provider: str = ""
    water_in_rent: str = ""
    sewer_system: str = ""
    sewer_provider: str = ""
    sewer_in_rent: str = ""
    septic_age: str = ""
    septic_last_pumped: str = ""
    septic_bedroom_rating: str = ""
    heating_type: str = ""
    heating_fuel: str = ""
    heating_fuel_in_rent: str = ""
    oil_tank_location: str = ""
    oil_company: str = ""
    oil_tank_size: str = ""
    gas_levels_measured: str = ""
    cooling_system: str = ""
    air_filters: str = ""
    electric_provider: str = ""
    electric_meter: str = ""
    electric_in_rent: str = ""
    trash_arrangement: str = ""
    trash_company: str = ""
    trash_day: str = ""
    trash_in_rent: str = ""
    internet_options: str = ""
    internet_in_rent: str = ""
    mail_arrangement: str = ""
    laundry_setup: str = ""
    lawn_care_in_rent: str = ""
    lawn_care_vendor: str = ""
    fireplace: str = ""
    fireplace_type: str = ""
    fireplace_works: str = ""
    fireplace_last_inspection: str = ""
    parking_arrangement: str = ""
    parking_capacity: str = ""
    pet_policy: str = ""
    pet_restrictions: str = ""
    tenant_names: str = ""
    tenant_contact: str = ""
    tenants_notified: str = ""
    current_rent: str = ""
    lease_end_date: str = ""
    deposit_amount: str = ""
    deposit_location: str = ""
    section_8: str = ""
    notes: str = ""


class OwnerOnboardOut(Schema):
    status: str
    id: int
