# Generated by Django 5.2.11 on 2026-05-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_add_financial_workflow_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ownerreportlog',
            new_name='reports_own_owner_i_962423_idx',
            old_name='reports_own_owner_i_idx',
        ),
        migrations.AlterField(
            model_name='ownerreportlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
