"""
Django settings for vesta_rental_index project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

_csrf_origins = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(",") if o.strip()]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "ninja",
    # Vesta apps
    "properties",
    "leasing",
    "market",
    "screening",
    "maintenance",
    "accounting",
    "integrations",
    "dashboard",
    "onboarding",
    "reports",
    "weekly_reports",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'dashboard.middleware.LoginRateLimitMiddleware',
    'dashboard.middleware.ForcePasswordChangeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vesta_rental_index.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vesta_rental_index.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default="postgresql://{user}:{password}@{host}:{port}/{name}".format(
            user=os.environ.get("POSTGRES_USER", "vesta"),
            password=os.environ.get("POSTGRES_PASSWORD", "vesta"),
            host=os.environ.get("POSTGRES_HOST", "db"),
            port=os.environ.get("POSTGRES_PORT", "5432"),
            name=os.environ.get("POSTGRES_DB", "vesta_rental_index"),
        )
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/dashboard/"

# Django-Ninja API
NINJA_PAGINATION_PER_PAGE = 100

# Rentvine API
RENTVINE = {
    "SUBDOMAIN": os.environ.get("RENTVINE_SUBDOMAIN", ""),
    "API_KEY": os.environ.get("RENTVINE_API_KEY", ""),
    "API_SECRET": os.environ.get("RENTVINE_API_SECRET", ""),
}

# RentEngine API
RENTENGINE = {
    "BASE_URL": os.environ.get(
        "RENTENGINE_BASE_URL", "https://app.rentengine.io/api/public/v1"
    ),
    "API_TOKEN": os.environ.get("RENTENGINE_API_TOKEN", ""),
    "WEBHOOK_SECRET": os.environ.get("RENTENGINE_WEBHOOK_SECRET", ""),
}

# BoomPay / BoomScreen API
BOOMPAY = {
    "BASE_URL": os.environ.get("BOOMPAY_BASE_URL", "")
    or "https://api.production.boompay.app",
    "API_KEY": os.environ.get("BOOMPAY_API_KEY", ""),
    "API_SECRET": os.environ.get("BOOMPAY_API_SECRET", ""),
    "WEBHOOK_SECRET": os.environ.get("BOOMPAY_WEBHOOK_SECRET", ""),
}

# Vesta API Authentication
# When set, all API endpoints require X-API-Key header. Unset = no auth (local dev).
VESTA_API_KEY = os.environ.get("VESTA_API_KEY", "")

# Email (SendGrid via django-anymail)
SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY", "")
SENDGRID_WEBHOOK_SECRET = os.environ.get("SENDGRID_WEBHOOK_SECRET", "")
SG_OWNER_REPORT_TEMPLATE_ID = os.environ.get(
    "SG_OWNER_REPORT_TEMPLATE_ID", "d-3083295c8c354ccfb8365e9cec9760ae"
)
SG_OWNER_REPORT_CC = os.environ.get("SG_OWNER_REPORT_CC", "accounting@vestapm.com")

# Local dev: route email to MailHog (SMTP on localhost:1025, web UI on localhost:8025)
# From inside Docker, MailHog on the host is reachable via host.docker.internal.
USE_MAILHOG = os.environ.get("USE_MAILHOG", "").lower() in ("1", "true", "yes")

if USE_MAILHOG:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ.get("MAILHOG_HOST", "mailhog")
    EMAIL_PORT = 1025
    EMAIL_USE_TLS = False
    EMAIL_HOST_USER = ""
    EMAIL_HOST_PASSWORD = ""
elif SENDGRID_API_KEY:
    EMAIL_BACKEND = "anymail.backends.sendgrid.EmailBackend"
    ANYMAIL = {"SENDGRID_API_KEY": SENDGRID_API_KEY}
    INSTALLED_APPS += ["anymail"]
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = os.environ.get("VESTA_FROM_EMAIL", "reports@vestapm.com")
VESTA_LOGO_URL = os.environ.get(
    "VESTA_LOGO_URL",
    "https://www.vestapm.com/images/logo.png",
)

# Showing outcome display: cancelled/missed columns in owner emails and
# Marketing Report page. Disabled because RentEngine's leasing_events webhook
# is not delivering — the only Showing data is a frozen May 19 bulk import.
# Re-enable once RentEngine webhook delivery is confirmed working.
SHOW_SHOWING_OUTCOMES = False

# Slack Bot
SLACK_BOT_TOKEN = os.environ.get("SLACK_BOT_TOKEN", "")
SLACK_SIGNING_SECRET = os.environ.get("SLACK_SIGNING_SECRET", "")
MINERVA_BOT_TOKEN = os.environ.get("MINERVA_BOT_TOKEN", "")
MINERVA_SIGNING_SECRET = os.environ.get("MINERVA_SIGNING_SECRET", "")

# Leasing Directory
SLACK_LEASING_WEBHOOK_URL = os.environ.get("SLACK_LEASING_WEBHOOK_URL", "")

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "maintenance": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "integrations.property_meld": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Anthropic
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")

# LeadSimple
LEADSIMPLE = {
    "BASE_URL": os.environ.get("LEADSIMPLE_BASE_URL") or "https://api.leadsimple.com/rest",
    "API_KEY": os.environ.get("LEADSIMPLE_API_KEY", ""),
}

# Property Meld
PROPERTY_MELD = {
    "BASE_URL": os.environ.get("PROPERTY_MELD_BASE_URL", "https://api.propertymeld.com/api/v2"),
    "CLIENT_ID": os.environ.get("PROPERTY_MELD_CLIENT_ID", ""),
    "CLIENT_SECRET": os.environ.get("PROPERTY_MELD_CLIENT_SECRET", ""),
    "MANAGEMENT_ID": os.environ.get("PROPERTY_MELD_MANAGEMENT_ID", ""),
    "DAILY_SUMMARY_CHANNEL": os.environ.get("PROPERTY_MELD_SUMMARY_CHANNEL", ""),
}
