# Generated by Django 5.2.14 on 2026-06-03 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emaildraft',
            name='comms_email_owner_i_8c607c_idx',
        ),
        migrations.AddConstraint(
            model_name='emaildraft',
            constraint=models.UniqueConstraint(fields=('product', 'owner', 'week_start'), name='unique_draft_per_owner_per_week'),
        ),
    ]
