# Generated by Django 5.2.14 on 2026-06-04 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0006_emaildraft_recipient_email'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioMonthlyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, default='monthly', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('financials_html', models.TextField(blank=True, default='', help_text='Rendered HTML fragment for the financials section (inline-styled for SendGrid).')),
                ('notes_html', models.TextField(blank=True, default='', help_text='Rendered HTML fragment for the narrative section (inline-styled for SendGrid).')),
                ('generated_note', models.TextField(blank=True, default='', help_text='AI-generated plain-text note (the raw output, before human review).')),
                ('approved_generated_note', models.TextField(blank=True, default='', help_text='Human-reviewed/edited version of generated_note. Blank = not yet reviewed.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], db_index=True, default='draft', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_notes', to='core.portfolio')),
            ],
            options={
                'indexes': [models.Index(fields=['period_type', 'period_start', 'status'], name='comms_portf_period__3670c1_idx')],
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'period_type', 'period_start'), name='unique_portfolio_note_per_period')],
            },
        ),
    ]
