# Generated by Django 5.2.11 on 2026-06-11 02:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0008_portfoliomaintenancenote'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDistributionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, default='monthly', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('distribution_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of 3250 Owner Distribution postings for the month.', max_digits=12)),
                ('distribution_date', models.DateField(blank=True, help_text="Latest datePosted among the month's distribution postings.", null=True)),
                ('line_items', models.JSONField(default=list, help_text='Per-property rent snapshot: [{"property_id": int, "property_address": str, "expected": "0.00", "collected": "0.00"}]')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_snapshots', to='core.portfolio')),
            ],
            options={
                'indexes': [models.Index(fields=['period_type', 'period_start'], name='comms_portf_period__05bcda_idx')],
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'period_type', 'period_start'), name='unique_distribution_snapshot_per_period')],
            },
        ),
    ]
