# Generated by Django 5.2.11 on 2026-06-12 03:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0009_portfoliodistributionsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodistributionsnapshot',
            name='undeposited_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Rent-only undeposited balance (receipts + prepayment receipts) at build time.', max_digits=12),
        ),
        migrations.AddField(
            model_name='portfoliodistributionsnapshot',
            name='undeposited_as_of',
            field=models.DateField(blank=True, help_text='Date the undeposited balance was pulled from RentVine.', null=True),
        ),
    ]
