# Generated by Django 5.2.11 on 2026-06-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0010_add_undeposited_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='sent_fragments',
            field=models.JSONField(blank=True, default=list, help_text='Per-portfolio sent fragments, frozen at send time: [{"portfolio_id": int, "portfolio_name": str, "period_start": "YYYY-MM-DD", "notes_html": str}]'),
        ),
    ]
