# Generated by Django 5.2.14 on 2026-06-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_meld_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('brief_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('work_type', models.CharField(blank=True, max_length=100)),
                ('work_location', models.CharField(blank=True, max_length=255)),
                ('origin', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.CharField(blank=True, db_index=True, max_length=20)),
                ('status', models.CharField(blank=True, db_index=True, max_length=100)),
                ('assigned_vendor_name', models.CharField(blank=True, max_length=255)),
                ('coordinator_name', models.CharField(blank=True, max_length=255)),
                ('property_address', models.CharField(blank=True, max_length=500)),
                ('property_meld_property_id', models.CharField(blank=True, max_length=255)),
                ('unit_ref', models.CharField(blank=True, max_length=255)),
                ('resident_presence_required', models.BooleanField(default=False)),
                ('scheduled_date', models.DateField(blank=True, db_index=True, null=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('marked_complete', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('owner_approval_status', models.CharField(choices=[('Not Requested', 'Not Requested'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Not Approved', 'Not Approved')], db_index=True, default='Not Requested', max_length=30)),
                ('has_invoice', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('reason_cannot_complete', models.TextField(blank=True)),
                ('resolution_type', models.CharField(blank=True, max_length=100)),
                ('parent_meld_id', models.CharField(blank=True, max_length=50)),
                ('recurring_meld_id', models.CharField(blank=True, max_length=50)),
                ('merged_meld_data', models.JSONField(blank=True, default=dict)),
                ('tenant_rating', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_modified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melds', to='core.unit')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'priority'], name='maintenance_status_5d8b35_idx'), models.Index(fields=['owner_approval_status', 'source_modified_at'], name='maintenance_owner_a_f0683b_idx'), models.Index(fields=['scheduled_date', 'status'], name='maintenance_schedul_1e2087_idx'), models.Index(fields=['marked_complete', 'has_invoice'], name='maintenance_marked__e627fe_idx')],
            },
        ),
    ]
