# Generated by Django 5.2.11 on 2026-02-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leasing', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_contact_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('liability_insurance_company', models.CharField(blank=True, max_length=255)),
                ('liability_insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('liability_insurance_expires', models.DateField(blank=True, null=True)),
                ('workers_comp_insurance_company', models.CharField(blank=True, max_length=255)),
                ('workers_comp_insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('workers_comp_insurance_expires', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_visible_tenant_portal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_id', models.IntegerField(db_index=True, unique=True)),
                ('primary_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Open'), (3, 'Closed'), (4, 'On Hold')])),
                ('name', models.CharField(max_length=255)),
                ('is_system_status', models.BooleanField(default=False)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'work order statuses',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_id', models.IntegerField(db_index=True, unique=True)),
                ('inspection_type', models.IntegerField(choices=[(1, 'Pre-Inspection'), (2, 'Move In'), (3, 'Move Out'), (4, 'Inspection')])),
                ('inspection_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Pending Maintenance'), (4, 'Completed')])),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='leasing.lease')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='properties.property')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='properties.unit')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_id', models.IntegerField(db_index=True, unique=True)),
                ('work_order_number', models.IntegerField(blank=True, null=True)),
                ('primary_status', models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Open'), (3, 'Closed'), (4, 'On Hold')], null=True)),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], null=True)),
                ('source_type', models.IntegerField(blank=True, choices=[(1, 'Portal'), (2, 'In Person'), (3, 'Email'), (4, 'Text Message'), (5, 'Phone'), (6, 'Recurring')], null=True)),
                ('description', models.TextField(blank=True)),
                ('vendor_instructions', models.TextField(blank=True)),
                ('closing_description', models.TextField(blank=True)),
                ('is_owner_approved', models.BooleanField(default=False)),
                ('is_vacant', models.BooleanField(default=False)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('scheduled_start_date', models.DateField(blank=True, null=True)),
                ('scheduled_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='leasing.lease')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='properties.unit')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.vendor')),
                ('vendor_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.vendortrade')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.workorderstatus')),
            ],
        ),
    ]
