# Generated by Django 5.2.11 on 2026-03-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_meld_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('brief_description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('priority', models.CharField(blank=True, db_index=True, max_length=20)),
                ('status', models.CharField(blank=True, db_index=True, max_length=100)),
                ('assigned_vendor_name', models.CharField(blank=True, max_length=255)),
                ('coordinator_name', models.CharField(blank=True, max_length=255)),
                ('property_address', models.CharField(blank=True, max_length=500)),
                ('property_meld_property_id', models.CharField(blank=True, max_length=255)),
                ('unit_ref', models.CharField(blank=True, max_length=255)),
                ('resident_presence_required', models.BooleanField(default=False)),
                ('scheduled_date', models.DateField(blank=True, db_index=True, null=True)),
                ('completed_date', models.DateField(blank=True, db_index=True, null=True)),
                ('owner_approval_status', models.CharField(choices=[('Not Requested', 'Not Requested'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Not Approved', 'Not Approved')], db_index=True, default='Not Requested', max_length=30)),
                ('has_invoice', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_modified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'priority'], name='maintenance_status_5d8b35_idx'), models.Index(fields=['owner_approval_status', 'source_modified_at'], name='maintenance_owner_a_f0683b_idx'), models.Index(fields=['scheduled_date', 'status'], name='maintenance_schedul_1e2087_idx'), models.Index(fields=['completed_date', 'has_invoice'], name='maintenance_complet_a4dfe1_idx')],
            },
        ),
    ]
