# Generated by Django 5.2.11 on 2026-06-17 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('maintenance', '0002_meld_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_id', models.IntegerField(db_index=True, unique=True)),
                ('work_order_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('priority_id', models.IntegerField(blank=True, null=True)),
                ('vendor_trade_id', models.IntegerField(blank=True, null=True)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vendor_contact_id', models.IntegerField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('is_internal', models.BooleanField(default=False)),
                ('is_vacant', models.BooleanField(default=False)),
                ('is_owner_approved', models.BooleanField(default=False)),
                ('is_shared_with_owner', models.BooleanField(default=False)),
                ('is_shared_with_tenant', models.BooleanField(default=False)),
                ('primary_work_order_status_id', models.IntegerField(blank=True, null=True)),
                ('work_order_status_id', models.IntegerField(blank=True, null=True)),
                ('vendor_work_order_status_id', models.IntegerField(blank=True, null=True)),
                ('portal_vendor_work_order_status_id', models.IntegerField(blank=True, null=True)),
                ('closed_by_user_id', models.IntegerField(blank=True, null=True)),
                ('cancelled_by_user_id', models.IntegerField(blank=True, null=True)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_modified_at', models.DateTimeField(blank=True, null=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('date_due', models.DateField(blank=True, null=True)),
                ('scheduled_start_date', models.DateField(blank=True, null=True)),
                ('scheduled_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='core.lease')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='core.portfolio')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='core.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='core.unit')),
            ],
            options={
                'indexes': [models.Index(fields=['primary_work_order_status_id'], name='maintenance_primary_1331ef_idx'), models.Index(fields=['date_closed', 'cancelled_by_user_id'], name='maintenance_date_cl_138567_idx')],
            },
        ),
    ]
