# Generated by Django 5.2.14 on 2026-06-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
