# Generated by Django 5.2.11 on 2026-05-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenanceemailmeld'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='maintenanceemailmeld',
            new_name='maintenance_portfol_c9ec5e_idx',
            old_name='maintenance_portfol_8f3c1a_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenanceemailmeld',
            new_name='maintenance_email_s_4386bc_idx',
            old_name='maintenance_email_s_4b2e7d_idx',
        ),
        migrations.RenameIndex(
            model_name='meld',
            new_name='maintenance_marked__e627fe_idx',
            old_name='maintenance_marked__a4dfe1_idx',
        ),
    ]
