# Generated by Django 5.2.11 on 2026-05-25 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_bill_discount_percent_and_more'),
        ('maintenance', '0005_rename_maintenance_portfol_8f3c1a_idx_maintenance_portfol_c9ec5e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='lease',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='property',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='vendor_trade',
        ),
        migrations.DeleteModel(
            name='WorkOrderStatus',
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
