# Generated by Django 5.2.11 on 2026-05-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_remove_workorder_lease_remove_workorder_property_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenditure',
        ),
    ]
