# Generated by Django 5.2.14 on 2026-06-01 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APISyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('rentvine', 'RentVine'), ('rentengine', 'RentEngine'), ('boompay', 'BoomPay/BoomScreen'), ('property_meld', 'Property Meld')], db_index=True, max_length=20)),
                ('endpoint', models.CharField(max_length=255)),
                ('sync_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='started', max_length=20)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API sync log',
                'verbose_name_plural': 'API sync logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
