# Generated by Django 5.2.11 on 2026-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APISyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('rentengine', 'RentEngine'), ('rentvine', 'RentVine'), ('boompay', 'BoomPay/BoomScreen')], db_index=True, max_length=20)),
                ('endpoint', models.CharField(max_length=255)),
                ('sync_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='started', max_length=20)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API sync log',
                'verbose_name_plural': 'API sync logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('rentengine', 'RentEngine'), ('rentvine', 'RentVine'), ('boompay', 'BoomPay/BoomScreen')], db_index=True, max_length=20)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('table_name', models.CharField(db_index=True, max_length=100)),
                ('record', models.JSONField(blank=True, default=dict)),
                ('old_record', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['source', 'table_name', 'event_type'], name='integration_source_e4cd49_idx'), models.Index(fields=['processed', 'received_at'], name='integration_process_8d0b68_idx')],
            },
        ),
    ]
