# Generated by Django 5.2.11 on 2026-05-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_pipelinerun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisynclog',
            name='source',
            field=models.CharField(choices=[('rentengine', 'RentEngine'), ('rentvine', 'RentVine'), ('boompay', 'BoomPay/BoomScreen'), ('property_meld', 'Property Meld')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='source',
            field=models.CharField(choices=[('rentengine', 'RentEngine'), ('rentvine', 'RentVine'), ('boompay', 'BoomPay/BoomScreen'), ('property_meld', 'Property Meld')], db_index=True, max_length=20),
        ),
    ]
