# Generated by Django 5.2.11 on 2026-05-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetUpdateRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Inclusive start of the reporting period')),
                ('end_date', models.DateField(help_text='Inclusive end of the reporting period')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='running', max_length=10)),
                ('sheets_found', models.IntegerField(default=0)),
                ('sheets_matched', models.IntegerField(default=0)),
                ('sheets_written', models.IntegerField(default=0)),
                ('sheets_skipped', models.IntegerField(default=0)),
                ('sheets_errored', models.IntegerField(default=0)),
                ('unmatched_sheets', models.JSONField(blank=True, default=list)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('dry_run', models.BooleanField(default=False)),
                ('force', models.BooleanField(default=False)),
                ('triggered_by', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
