# Generated by Django 5.2.11 on 2026-05-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_reports', '0003_add_owner_email_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneremailsend',
            name='week_date',
            field=models.DateField(help_text="Monday of the ISO calendar week containing the period's Tuesday start (i.e. the day before a Tue–Mon reporting window opens). Must match PropertyWeeklyNote.week_date exactly."),
        ),
    ]
