# Generated by Django 5.2.11 on 2026-05-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_reports', '0006_rename_blurb_model_and_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owneremailblurb',
            options={'ordering': ['-week_date']},
        ),
    ]
