# Generated by Django 5.2.11 on 2026-05-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_reports', '0007_alter_owneremailblurb_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='owneremailsend',
            name='email_type',
            field=models.CharField(blank=True, default='weekly_leasing', max_length=50),
        ),
        migrations.AddField(
            model_name='owneremailsend',
            name='recipient_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='owneremailsend',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
