# Generated by Django 5.2.11 on 2026-03-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneronboard',
            name='bathrooms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
