# Generated by Django 5.2.11 on 2026-03-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_owneronboard_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneronboard',
            name='bathrooms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='cooling_system',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='current_rent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='deposit_amount',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='electric_in_rent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='electric_meter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='fireplace',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='fireplace_last_inspection',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='fireplace_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='fireplace_works',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='gas_levels_measured',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='heating_fuel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='heating_fuel_in_rent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='heating_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='hoa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='internet_in_rent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='lawn_care_in_rent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='lease_end_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='occupied',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='oil_tank_size',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='owner1_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='owner2_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='parking_capacity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='pet_policy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='plan',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='poc_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='property_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='property_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='property_zip',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='section_8',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='septic_age',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='septic_bedroom_rating',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='septic_last_pumped',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='sewer_in_rent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='sewer_system',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='tenants_notified',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='transferring_pm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='trash_arrangement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='trash_day',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='trash_in_rent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='warranty',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='water_in_rent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owneronboard',
            name='water_source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
