from django.conf import settings
from django.db import models


class VoiceGuide(models.Model):
    """
    Tone and style instructions for a product's AI-generated email content.
    One row per product type (e.g. "maintenance", "owner_report").
    ADMIN-editable only.
    """

    product = models.CharField(max_length=50, unique=True, db_index=True)
    instructions = models.TextField()
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return f"VoiceGuide: {self.product}"


class EmailDraft(models.Model):
    """
    A reviewable email draft generated by the comms engine.
    Stored as rendered HTML — reviewable, editable, and auditable.
    Sending is handled separately; nothing here triggers delivery.
    """

    STATUS_CHOICES = [
        ("draft", "Draft"),
        ("approved", "Approved"),
        ("sent", "Sent"),
    ]

    product = models.CharField(max_length=50, db_index=True)
    owner = models.ForeignKey(
        "core.Owner",
        on_delete=models.CASCADE,
        related_name="email_drafts",
    )
    subject = models.CharField(max_length=500)
    body_html = models.TextField()
    generated_note = models.TextField(blank=True, default="")
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default="draft", db_index=True
    )
    generated_at = models.DateTimeField(auto_now_add=True)
    sent_at = models.DateTimeField(null=True, blank=True)
    sent_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    PERIOD_TYPE_CHOICES = [
        ("weekly", "Weekly"),
        ("monthly", "Monthly"),
    ]
    period_type = models.CharField(
        max_length=10, choices=PERIOD_TYPE_CHOICES, default="weekly", db_index=True
    )
    period_start = models.DateField()
    period_end = models.DateField()

    class Meta:
        indexes = [
            models.Index(fields=["product", "status"]),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=["product", "owner", "period_type", "period_start"],
                name="unique_draft_per_owner_per_period",
            ),
        ]

    def __str__(self):
        return f"{self.product} draft for {self.owner} ({self.period_start})"
