# Generated by Django 5.2.14 on 2026-06-03 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0002_meld_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_id', models.IntegerField(db_index=True, unique=True)),
                ('bill_date', models.DateField()),
                ('date_due', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('payment_memo', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meld', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='maintenance.meld')),
            ],
        ),
        migrations.CreateModel(
            name='BillCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_transaction_id', models.IntegerField(db_index=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='accounting.bill')),
            ],
            options={
                'indexes': [models.Index(fields=['bill'], name='accounting__bill_id_bb758b_idx')],
            },
        ),
    ]
