# Generated by Django 5.2.11 on 2026-02-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_id', models.IntegerField(db_index=True, unique=True)),
                ('ledger_type', models.IntegerField(choices=[(1, 'Manager'), (2, 'Portfolio'), (3, 'Property'), (4, 'Unit')])),
                ('object_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_id', models.IntegerField(db_index=True, unique=True)),
                ('bill_type_id', models.IntegerField(blank=True, null=True)),
                ('payee_contact_id', models.IntegerField(blank=True, null=True)),
                ('bill_date', models.DateField()),
                ('date_due', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('payment_memo', models.TextField(blank=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('markup_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='maintenance.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_id', models.IntegerField(db_index=True, unique=True)),
                ('account_type_id', models.IntegerField()),
                ('account_category_id', models.IntegerField(blank=True, null=True)),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_rent', models.BooleanField(default=False)),
                ('is_deposit', models.BooleanField(default=False)),
                ('is_escrow', models.BooleanField(default=False)),
                ('is_prepayment', models.BooleanField(default=False)),
                ('is_management_fee', models.BooleanField(default=False)),
                ('is_subject_to_management_fees', models.BooleanField(default=False)),
                ('is_subject_to_late_fees', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to='accounting.chartofaccounts')),
            ],
            options={
                'verbose_name_plural': 'chart of accounts',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_id', models.IntegerField(db_index=True, unique=True)),
                ('transaction_type', models.IntegerField(choices=[(1, 'Lease Charge'), (2, 'Lease Payment'), (3, 'Lease Credit'), (4, 'Lease Payment Return'), (5, 'Owner Payment'), (6, 'Owner Payment Return'), (7, 'Bill Charge'), (8, 'Bill Payout Charge'), (9, 'Bank Fee'), (10, 'Bank Transfer'), (11, 'Journal Entry'), (12, 'Other Payment'), (13, 'Other Payment Return'), (14, 'Management Fee'), (15, 'Ledger Transfer'), (16, 'Ledger Payout'), (17, 'Ledger Payout Return'), (18, 'Bill Payout Charge Return'), (19, 'Lease Deposit Release Credit'), (20, 'Lease Payout'), (21, 'Lease Payout Return'), (22, 'Bill Credit'), (23, 'Bill Payout Credit'), (24, 'Bill Payout Credit Return')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('is_voided', models.BooleanField(default=False)),
                ('date_posted', models.DateField(db_index=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.bill')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='properties.portfolio')),
                ('primary_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.ledger')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='properties.unit')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='TransactionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_id', models.IntegerField(db_index=True, unique=True)),
                ('entry_type', models.IntegerField(choices=[(1, 'Credit'), (2, 'Debit')])),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('is_cash', models.BooleanField(default=False)),
                ('is_accrual', models.BooleanField(default=False)),
                ('date_posted', models.DateField(db_index=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='accounting.chartofaccounts')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='accounting.ledger')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounting.transaction')),
            ],
            options={
                'verbose_name_plural': 'transaction entries',
            },
        ),
    ]
