# Generated by Django 5.2.11 on 2026-05-25 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('maintenance', '0005_rename_maintenance_portfol_8f3c1a_idx_maintenance_portfol_c9ec5e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='markup_percent',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='work_order',
        ),
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='meld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='maintenance.meld'),
        ),
        migrations.CreateModel(
            name='BillCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvine_transaction_id', models.IntegerField(db_index=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('primary_ledger_id', models.IntegerField(blank=True, null=True)),
                ('property_id', models.IntegerField(blank=True, null=True)),
                ('unit_id', models.IntegerField(blank=True, null=True)),
                ('charge_account_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='accounting.bill')),
            ],
            options={
                'indexes': [models.Index(fields=['bill'], name='accounting__bill_id_bb758b_idx')],
            },
        ),
    ]
