# Generated by Django 5.2.11 on 2026-06-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_portfoliostatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='work_order_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='RentVine workOrderID from /accounting/bills. Join to WorkOrder.rentvine_id — no FK to avoid sync-ordering coupling.', null=True),
        ),
    ]
